import type {Column,Dataset} from './data';
export function quantile(sorted:number[],p:number){if(!sorted.length)return null;const h=(sorted.length-1)*p,i=Math.floor(h),f=h-i;return sorted[i]+f*(sorted[Math.min(i+1,sorted.length-1)]-sorted[i])}
export function stats(values:number[]){const a=[...values].sort((x,y)=>x-y),n=a.length;if(!n)return null;const mean=a.reduce((s,v)=>s+v,0)/n,q1=quantile(a,.25)!,q3=quantile(a,.75)!;return {n,mean,median:quantile(a,.5)!,sd:n>1?Math.sqrt(a.reduce((s,v)=>s+(v-mean)**2,0)/(n-1)):null,min:a[0],q1,q3,max:a[n-1],iqr:q3-q1,outliers:a.filter(v=>v<q1-1.5*(q3-q1)||v>q3+1.5*(q3-q1)).length}}
function rank(a:number[]){const sorted=a.map((v,i)=>({v,i})).sort((x,y)=>x.v-y.v),out=Array(a.length);for(let i=0;i<sorted.length;){let j=i+1;while(j<sorted.length&&sorted[j].v===sorted[i].v)j++;for(let k=i;k<j;k++)out[sorted[k].i]=(i+j+1)/2;i=j}return out as number[]}
export function pearson(x:number[],y:number[]){if(x.length<3)return null;const n=x.length,mx=x.reduce((a,b)=>a+b,0)/n,my=y.reduce((a,b)=>a+b,0)/n;let xx=0,yy=0,xy=0;for(let i=0;i<n;i++){const a=x[i]-mx,b=y[i]-my;xx+=a*a;yy+=b*b;xy+=a*b}return xx&&yy?xy/Math.sqrt(xx*yy):null}
export function correlation(x:number[],y:number[]){return {pearson:pearson(x,y),spearman:pearson(rank(x),rank(y)),n:x.length}}
export function numeric(ds:Dataset,i:number){return ds.rows.map(r=>r[i]===null?null:Number(r[i])).filter((x):x is number=>x!==null&&Number.isFinite(x))}
export function pairs(ds:Dataset,a:number,b:number){const x:number[]=[],y:number[]=[];for(const row of ds.rows){if(row[a]===null||row[b]===null)continue;const p=Number(row[a]),q=Number(row[b]);if(Number.isFinite(p)&&Number.isFinite(q)){x.push(p);y.push(q)}}return{x,y}}
export function frequencies(ds:Dataset,i:number){const m=new Map<string,number>();for(const row of ds.rows){const v=row[i];if(v!==null)m.set(v,(m.get(v)||0)+1)}return [...m].sort((a,b)=>b[1]-a[1])}
export function histogram(values:number[]){const s=stats(values);if(!s)return[];let count=s.iqr>0?Math.ceil((s.max-s.min)/(2*s.iqr/Math.cbrt(s.n))):Math.ceil(Math.sqrt(s.n));count=Math.max(5,Math.min(50,count||5));const width=(s.max-s.min||1)/count,bins=Array.from({length:count},(_,i)=>({label:(s.min+i*width).toFixed(2),count:0}));for(const v of values)bins[Math.min(count-1,Math.floor((v-s.min)/width))].count++;return bins}
export function analyze(ds:Dataset,columns:Column[],targetId?:string){const missing=columns.reduce((s,c)=>s+c.missing,0),seen=new Set<string>();let duplicates=0;for(const row of ds.rows){const key=JSON.stringify(row);if(seen.has(key))duplicates++;else seen.add(key)}const numericCols=columns.filter(c=>c.kind==='numeric'&&c.role!=='identifier'&&c.role!=='ignored');const summaries=numericCols.map(c=>({column:c,stats:stats(numeric(ds,Number(c.id)))}));const target=columns.find(c=>c.id===targetId&&c.role==='target')||columns.find(c=>c.role==='target');const related=target&&['numeric','ordinal'].includes(target.kind)?numericCols.filter(c=>c.id!==target.id).map(c=>{const p=pairs(ds,Number(c.id),Number(target.id));return{column:c,...correlation(p.x,p.y)}}).sort((a,b)=>Math.abs(b.pearson||0)-Math.abs(a.pearson||0)):[];return{rowCount:ds.rows.length,columnCount:columns.length,missing,duplicates,constants:columns.filter(c=>c.unique<=1),summaries,related,target,warnings:ds.errors}}
